version: '2'

services:
    django:
        build: .
        restart: unless-stopped
        command: uwsgi --master --http :80 -p 4 --die-on-term --module django.core.wsgi:get_wsgi_application() --logto /logs/uwsgi.log
        environment:
            - DJANGO_SETTINGS_MODULE=microline.settings
            - PRODUCTION_ENV=yes
        volumes:
            - .:/app
            - ./logs:/logs

    # postgres:
    #     image: postgres:9
    #     restart: unless-stopped
    #     environment:
    #         - POSTGRES_PASSWORD=ooy34ao78b4o

    mysql:
        image: mysql
        command: --character-set-server=utf8
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=h34bh77f78fkf23kg
            - MYSQL_USER=microline
            - MYSQL_PASSWORD=kfkyfwkyuwf4ky
            - MYSQL_DATABASE=microline
        volumes:
            - ./_data/mysql:/var/lib/mysql

    nginx:
        image: nginx
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./static:/static
            - ./media:/media
            - ./logs:/var/log/nginx
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=microline.ru,www.microline.ru
            - LETSENCRYPT_HOST=microline.ru
            - LETSENCRYPT_EMAIL=ilya@microline.ru

    exim:
        build: docker/exim
        restart: unless-stopped
        environment:
            - PRIMARY_HOST=microline.ru
            - ALLOWED_HOSTS=0.0.0.0/0
            - DKIM_SELECTOR=exim
        volumes:
            - ./etc/exim:/etc/exim-orig
            - ./etc/dkim:/dkim
            - ./_data/exim/spool:/var/spool/exim4
            - ./_data/exim/saved:/exim-saved
            - ./_data/exim/logs:/var/log/exim4
